### ISSUE TITLE
new phpminer_rpcclient issues

### ISSUE THREAD

**Issue by DanielNagy** [prdatur/phpminer#12]
The linux_rpcclient_setup.sh file exits prematurely due to a misplaced exit command.

rpcclient screen session starts. but its unable to start cgminer screen session

removed the unlink /tmp/startcg, and manually ran it, and it works fine, but rpc client is unable to start cgminer again if requested.

**Comment by DanielNagy** [comment]
and there is 2 config files.. config.dist.php and config.php the setup.sh file doesn't configure it properly.

**Comment by DanielNagy** [comment]
Sorry, Starting issue was because i selected the wrong user to start as.. The other issues still apply regarding the setup.sh file exiting

**Comment by prdatur** [comment]
I pushed the fix to also configurate the cgminer api ip + port, can you please check again what happens now? 
The 2 config files are correct. i had to add the miner api ip + port within the config.php but the install script should not touch the 'dist' file. This is just a fallback when the config key within the normal config.php doesn't exist.

the exit was a forgotten debug exit :) sorry :)

**Comment by DanielNagy** [comment]
should update the setup text 

Please enter the user on which phpminer_rpcclient should run:

to

Please enter the user on which your miner application should run:

as the rpcclient runs as root (sudo screen -r) to attach..

**Comment by DanielNagy** [comment]
cgminer doesnt start on boot of pc
