### ISSUE TITLE
add Pushover notification - free one

### ISSUE THREAD

**Issue by piotrasd** [prdatur/phpminer#14]
Hi
Please add or replace RapidPush on Pushover 

Pushover dont have any limits of massages per day like other and is free
also i compatible for iOS and Android and have the most easy API to provide
(over bash, perl, php, ruby)

Please just look on page
https://pushover.net and sample code

Im using on my iPhone 1 year with other apps and never i had any problems
When i saw today on my friend phone (android) RapidPush and limit 5 msg per day and adverts
i just say WTF :/

**Comment by prdatur** [comment]
Sorry I leave RapidPush as the Android notification service, because the way to the support is much closer, approximate 1 mm, I am the developer of RapidPush, so I prefer my own Service. But thanks for the input.
