### ISSUE TITLE
Warning: reset() expects parameter 1 to be array, boolean given

### ISSUE THREAD

**Issue by nicoschtein** [prdatur/phpminer#17]
I'm getting this warning in many setups and only one rig is displayed, and only the header and no rows for gpus. 

```
Warning: reset() expects parameter 1 to be array, boolean given in /var/phpminer/controllers/main.php on line 971
```

**Comment by prdatur** [comment]
Please check it with the new update. I didn't changed anything at this line. But I want just to be sure that the error still exists.

**Comment by prdatur** [comment]
Did the error occured again?

**Comment by nicoschtein** [comment]
It is weird, the website hangs waiting for an offline rig to respond so i can't actually say if it still does...

**Comment by nicoschtein** [comment]
After 2 minutes of waiting it does load fine with all rigs except the one that is not online but with this error printed:

```
Warning: socket_recv(): unable to read from socket [104]: Connection reset by peer in .../phpminer/includes/PHPMinerRPC.class.php on line 937
```

**Comment by prdatur** [comment]
will check it. maybe i forgot a timeout somewhere.

**Comment by nicoschtein** [comment]
I think the timeout is there, but it is not being used by PHP.
Are you setting `stream_set_blocking()` to `true` ?

**Comment by nicoschtein** [comment]
After checking the code, i see you are setting the timeout with a function used for `streams` and you are using `sockets` that is not going to work.

https://github.com/prdatur/phpminer/blob/master/includes/PHPMinerRPC.class.php#L893-L894

**Comment by prdatur** [comment]
thx

**Comment by prdatur** [comment]
Have pushed the changes, please check if it is working now.

**Comment by nicoschtein** [comment]
It worked for a while, timeout is fixed, but i dont get any rig listed and got this error multiple times (looks like once per GPU) at the end of the page:

```
Error: WARNING: reset() expects parameter 1 to be array, boolean given in /phpminer/controllers/main.php on line 1025
Backtrace:
File: /var/phpminer/index.php
Line: 155: call_user_func_array (Args: array(), array())
File: (unknown)
Line: (unknown): main->init (no args)
File: /var/phpminer/controllers/main.php
Line: 452: main->get_device_data (Args: 1)
Line: 925: main->get_detailed_rig_data (Args: "RIG-NAME", 1)
Line: 1025: reset (Args: 1)
```

**Comment by nicoschtein** [comment]
Weird thing, it fixed itself... But nonetheless it will happen again

**Comment by nicoschtein** [comment]
Nope, it did not fix itself, my bad, disregard the last message..

**Comment by prdatur** [comment]
I have checked it and i also got some bug reports with this error.
I assume the miner had no pools configured? Because this error determines that the miner api command "pools" had an empty response.
Please check it again and tell me if it now works or if now other magic things happend :)

**Comment by nicoschtein** [comment]
The "server" has a cgminer running fine (with pool from group configured by phpminer) , also 2 other clients are running fine too one with sgminer and one with cgminer. None of the 3 appear in phpminer web, and the error i pasted above is still showing up. :(

**Comment by prdatur** [comment]
With the latest commit the error can't be showing up. If there is an error, it must be a bit different. Because i really check if it is an array and if not i create an empty one.
Can you please verify you are on the latest version and if so please repost the error message.
If it is really the same error message also the same line etc. I have to recheck it.

**Comment by prdatur** [comment]
I think this error was in conjunction with the sgminer issue. If not make a new report please.
