### ISSUE TITLE
_rb_ Token for userbased pools

### ISSUE THREAD

**Issue by nicoschtein** [prdatur/phpminer#18]
I am having a hard time getting a pool to support myuser_rb_workername format.
Normally they use a `.` (dot) to split username and workername.

I know sometime ago @prdatur explained why the need for `_rb_` but can we just replace that token with `.` ? I will check the code to make sure i am not saying rubbish, but without looking this seems pretty valid following a normal logic.
@prdatur can you explain again the need for `_rb_` as in why not another token please?

**Comment by prdatur** [comment]
You wrote the reason already :) The pools are using the dot and that's why some pools don't allow the . within the worker name. I tried it, i think it was on netdoge or on hashfaster, and it doesn't let me change it to a worker with a dot.

**Comment by nicoschtein** [comment]
Wait, i think we are talking about two different things here.

I want phpminer to be like this:

```
Pool: stratum+tcp://...
User: nicoschtein
Pass: x
User based: YES
```

And each worker should be `nicoschtein.rig1`, `nicoschtein.rig2`,
`nicoschtein.rig3`, and not `nicoschtein_rb_rig1`.
So in the pool the worker name is just `rig1`.

**Comment by prdatur** [comment]
ah you mean the main user without the actual worker and the rig name will be the normal worker.. kk think this is not a bad idea. Have to check if this all works well.

**Comment by nicoschtein** [comment]
Great, i will wait for you to test this then

**Comment by extera-nl** [comment]
This would indeed be very usefull! Let me know if I can also help testing.

**Comment by prdatur** [comment]
I have changed it to .rb the "rb" is needed when gather pool information from the cgminer/sgminer itself and recognize that it is a rig based pool account. Else only with a dot i can not check if it is a normal pool or a rig based.
So for now it is:
user = test
rig 01 shortname = hello

username which will be used = test.rbhello
