### ISSUE TITLE
[REQUEST] Rename Pool Groups

### ISSUE THREAD

**Issue by nicoschtein** [prdatur/phpminer#19]
Add an edit symbol next to the pool group name to show pop up textfield (like the one in pool edit).
Right now clicking on the pool group name toggles show/hide...

**Comment by prdatur** [comment]
Will check, I had the idea in the beginning too but i have decided for some reasons, not to allow it :P maybe it had something to do to find out the current active pool group or change a group which is currently active somewhere.
