### ISSUE TITLE
[REQUEST] Incorporate coinvert selection for multiple cgminer "flavor" selection.

### ISSUE THREAD

**Issue by neurocis** [prdatur/phpminer#20]
Love the project, any possibility of incorporating coinvert into the rpc for miner/algo selection via the gui?

https://github.com/neurocis/coinvert

**Comment by prdatur** [comment]
In the next time i will implement a feature where you can choose within a pool group which mining algo should be used. Than the rpc client will just tell which algo is available.
This depends only to the api, the miner software which is used for the algo needs to have the api commands which rpc client uses.

**Comment by extera-nl** [comment]
prdatur,

if you need some help testing.... I have a SMOS 1.3 install running with the following miners in /opt/miners
- cgminer (3.7.2)
- vertminer-gpu (0.5.3)
- cgminer-keccak (3.7.3)

I have already tested most functions from phpminer with these miners, and they all worked.
Now we just need a way to switch between them (unfortunately, i lack knowledge of php to help with this).

maybe i can help providing installation scripts / instructions with for these miners on SMOS / linux?

**Comment by prdatur** [comment]
if there are any special actions you need to take on one of the miner software, than I would happy to know them :P

**Comment by neurocis** [comment]
So that would require a customized miner to implement the API for each algo or algos it supports?

**Comment by DanielNagy** [comment]
As i also currently switch between the 3 miners listed above, Having this ability all built into the Web ui would be handy.

Currently my "hack" involves me having 3 variations of the config.php file in the rpcclient directory. each setup individually for each coin. I currently replace the config file with the appropriate config for that coin, kill the screen sessions for rpc client and miner, and wait for it to restart. Painful, but best option i have.
I to am not a very good php coder, so i'm not much of a help :/

**Comment by DanielNagy** [comment]
Anyways, this was the same request as https://github.com/prdatur/phpminer/issues/4

**Comment by neurocis** [comment]
Sorry I missed request 4 ... coinvert currently features a scripted miner builder, but approaches the replacement of the miner by "cloaking" it as if it were the usual cgminer from BAMTs perspective, that way all BAMT and PHPMiner functions remain the same without need for further tweaking. I am currently working on a stealth way to accommodate command line options for multi-algo miners, possibly porting to php/python for my windows friends.

**Comment by neurocis** [comment]
Closing case - a few different methodologies of accomplishing the same thing. Opened #30 which would address this together with opening up the door for further user enhancements.
