### ISSUE TITLE
Slow init of session

### ISSUE THREAD

**Issue by sh1ny** [prdatur/phpminer#26]
When using filesystem to store sessions, sometimes initalizing session is slow sometimes. Only when using Access Management. More info here : 

http://stackoverflow.com/questions/10385582/session-start-seems-to-be-very-slow-but-only-sometimes

There is 2 solutions : 
1. Use database to store sessions
2. Use the following fix : 

``` php
--- a/includes/Session.class.php
+++ b/includes/Session.class.php
@@ -97,6 +97,7 @@ class Session
                if (empty($tmp_sessid)) {
                        session_start();
                        $this->session_id = session_id();
+                       session_write_close();
                }
                else if (empty($this->session_id)) {
                        $this->session_id = $tmp_sessid;
@@ -112,4 +113,4 @@ class Session
                return $this->session_id;
        }

-}
\ No newline at end of file
+}
```

**Comment by prdatur** [comment]
Solution 2 is not possible, because then i can not write or delete to the  session.
And yes the session is only used when access management is active.
In a normal env. it should not be such a problem with the session. I encountered this problem only on a real high cpu consume application on my dev life. 
So how much slower it is? And it is really worth the time? How often does it happen?

**Comment by sh1ny** [comment]
I was getting all the time for some reason. Most of the time, like after i open phpminer, spend some time there and just leave the tab open. After 7-10 minutes try to refresh or w/e and the page is stuck on loading. I am using nginx + php5-fpm and i enabled slow log on php5-fpm and it pointed me to the session_start(); line.

**Comment by prdatur** [comment]
How long have you wait then? is it worth to spend hours on it? because my time is limited :P

**Comment by prdatur** [comment]
I have added the session write close after the last (currently it is only at one position) session write finished. So this should speed up.
