### ISSUE TITLE
[?] Are config/* files still used?

### ISSUE THREAD

**Issue by nicoschtein** [prdatur/phpminer#28]
I want to know which files are still needed and which are replaced by MySQL.

I have right now:

```
phpminer/config# tree
.
|-- access.json
|-- config.json
|-- config.php
|-- config.php.dist
|-- notify.json
|-- phpminer.db
`-- pools.json
```

**Comment by prdatur** [comment]
only config.php and config.php.dist are important, i didn't auto deleted the old ones so a backup exists.

**Comment by nicoschtein** [comment]
Ok, so where is each rig connection info stored? I am trying to debug something and would like to delete a rig manually, currently the site wont list my rigs...

**Comment by prdatur** [comment]
mysql table "config", column "type" => "rigs"

**Comment by nicoschtein** [comment]
Ok, then i don't know whats wrong, i have 3 rigs listed there and they
don't show up...
All rigs and server are on latest version.
I will try to check for errors in logs and report.

2014-03-10 12:48 GMT-03:00 Christian notifications@github.com:

**Comment by nicoschtein** [comment]
Here:

init.js line 1391

```
Uncaught TypeError: Cannot read property 'Enabled' of undefined 
```

**Comment by prdatur** [comment]
Then your miner didn't returned any valid gpu information. Could you we make a teamviewer session so i can debug what the result of the cgminer api is?

**Comment by prdatur** [comment]
I will now shortly create the feature for custom start / stop commands. After that i will create a script for rpc clients where it will check all required api commands to cgminer. This i need also for the multi miner feature, so we can check if the api returns the correct things on the rpc client side.

**Comment by prdatur** [comment]
Please test if the api is working. 
php -f phpminer_rpcclient/test_api_commands.php

**Comment by nicoschtein** [comment]
On the server itself that has a client too it returns 

```
/phpminer# php -f phpminer_rpcclient/test_api_commands.php
The given miner api is compatible with PHPMiner and fully functional
```

But on the other two clients:

```
/phpminer# php -f phpminer_rpcclient/test_api_commands.php

11.03.2014 04:50:43: Check for provileged access: OK
11.03.2014 04:50:43:
PHP Warning:  reset() expects parameter 1 to be array, null given in /phpminer/phpminer_rpcclient/includes/CGMinerAPI.class.php on line 239
11.03.2014 04:50:43: GPU's found: ERROR: 0 found
11.03.2014 04:50:43: Value: false
11.03.2014 04:50:43: Please fix the error above
```

**Comment by nicoschtein** [comment]
Well, i finally found what is wrong, SGMiner is not working, but CGMiner does work! Changed all SG to CGMiner and phpminer works fine now.

**Comment by prdatur** [comment]
Ok but now i think it would be good to check what the problem is with sgminer. Can you tell me which version you have from sgminer? so i can check this.

**Comment by prdatur** [comment]
I just checked my sgminer and it worked so far. I think your sgminer is damaged or maybe the gpu is not recognized by sgminer, don't know.
