### ISSUE TITLE
[REQUEST] Generic fire custom command

### ISSUE THREAD

**Issue by neurocis** [prdatur/phpminer#30]
In the spirit of #22, What about a pulldown for custom commands/actions that can be fired on the target rig (understanding they would also have to exist on that rig). This would open up a world of possibilities. Activating/changing a mining schedule, swapping out miners and configurations, et al.

**Comment by prdatur** [comment]
Loved this feature, so i implemented it. Was not so complex. Can you please check if it is what you throught and if it works ?

**Comment by neurocis** [comment]
OK, I found the configuration in the rpcclient config.php. This I must say works sweet w/coinvert. I especially like the way you implemented with the option to confirm as well as getting the stdout results.

Cheers!

**Comment by prdatur** [comment]
:) Yea, I thought there might be some commands which are dangerous :) So happy customizing :)
