### ISSUE TITLE
1.3.1 - unable to change groups

### ISSUE THREAD

**Issue by JBrace1990** [prdatur/phpminer#31]
It keeps telling me that the sgminer/cgminer config file is not editable, however it has 777 permissions on it. 

I'm using bamt 1.3 and 1.5, and both rigs are having the issue. 

The rpcclient on both have been updated and restarted.

**Comment by prdatur** [comment]
did you configurated the correct cgminer config path within rpc client config.php?

**Comment by JBrace1990** [comment]
I just did, which fixed that issue, but now I'm getting this issue when I try to change groups:

Access denied to 'addpool' command

**Comment by prdatur** [comment]
Then please check your cgminer config that you have priviledge access for the api (W prefix)
api-allow: "W:your_ip"

**Comment by JBrace1990** [comment]
I have that added, and it was working fine with 1.2, but I can't get it to work right with this version. 

I may have this setup odd though.

So i have 1 server thats always on, and isn't a bamt RIG, then I have 2 rigs. All are connected through LAN, and I access the web host from wherever I am.

Just to test, I added in the IP of where I am and it isn't working, but I also have 127.0.0.1 and the 192.168.1.0/24 of my local.

**Comment by prdatur** [comment]
please post your api-allow line

**Comment by JBrace1990** [comment]
"api-allow": "W:192.168.1.0/24,127.0.0.1,72.248.!.130,64.30.81.!",

It doesn't actually have the !s, I just want to mask my IP some.

**Comment by prdatur** [comment]
Please add the "W" also in front of 127.0.0.1
and you can remove it from 192.168.1.0
The new phpminer just connects directly from the rpc client to the cgminer. that's why you didn't need to provide the cgminer ip while adding rigs.

**Comment by JBrace1990** [comment]
Perfect, that fixed it. I wasn't aware you needed to add write permissions to each IP, I thought it was just enabled for all.

**Comment by prdatur** [comment]
no prob.
