### ISSUE TITLE
cronjob cron.php references now unused /config/config.json

### ISSUE THREAD

**Issue by neurocis** [prdatur/phpminer#33]
Just upgraded to latest and purged my unused config files but it appears cron.php still references config.json as opposed to mysql db for configuration resulting in notification and auto task failure:

cron.php

```
// Get the system config.
$config = new Config(SITEPATH . '/config/config.json');

// Can't do anything if nothing is configurated.'
if ($config->is_empty()) {
    unlock();
    exit;
}
```

**Comment by prdatur** [comment]
thx

**Comment by prdatur** [comment]
Sorry closed it to fast, the string it self was never used with the newest version. It just was provided but there is no constructor in config which takes this path.
What exactly don't work with notifications?

**Comment by neurocis** [comment]
Hmm, I just pulled the latest commit, but get the dreaded (same as before), thought it was exiting as config.json no longer existed (only had this issue after clearing out the config files):
- The cronjob has not been executed since 5 minutes. Please check your cronjob config.

Manually firing cron.php gives the usual 'PHP Warning:  Module 'PDO' already loaded in Unknown on line 0' error, and I have verified /etc/cron.d/phpminer exists and is correct.

As I said, this only started happening since clearing out the unused config files.

**Comment by neurocis** [comment]
Grrr, fixed, orphan /tmp/phpminer_cron.pid, and multiple defunct cron.php processes.

removal fixed.

**Comment by prdatur** [comment]
That is another issue which I will now open, the cron job is sometimes defunc and i don't know why.
