### ISSUE TITLE
cronjob does not finish

### ISSUE THREAD

**Issue by prdatur** [prdatur/phpminer#38]
Sometimes it happens that the cronjob never ends. Need to be fixed.

**Comment by prdatur** [comment]
Maybe the issue was that the connection to the rpc client was sometimes broken. Have pushed a new semaphore and a retry feature, so we will see if fix the issue.

**Comment by neurocis** [comment]
There is some progress here, now I see the error not being able to connect to the RPC Client. What I see on my miner when this happens is a soft-hung miner process. It is like the RPC client gets hung trying to communicate with the miner API.

Looking at the screen of the rpc client I see the frontend repeating queries for pool information, however the miner screen is frozen, but does respond to a "q" and then hangs as defunct, resolution being a manual 'coldreboot -f'. I suspect the frontend is not getting results from the rpc client and rpc client is getting a connection to the miner API, but no reply in a timely fashion to its pool queries. The hang condition is then not being detected, and the rpc client non-responsive to a reboot/stop/start command.

**Comment by prdatur** [comment]
After running 3 days without an error i assume the problem has gone with the latest fixes.

**Comment by neurocis** [comment]
Reopen - whatever was happening in sgminer did not happen until now, but captured the following error from the phpminer_rpclcient screen:

```
PHP Warning:  socket_recv(): unable to read from socket [11]: Resource temporarily unavailable in /var/www/phpminer/phpminer_rpcclient/includes/RPCClientConnection.class.php on line 182
```

Hope that helps!
