### ISSUE TITLE
PHPMAILER hard configured to use SSL

### ISSUE THREAD

**Issue by DanielNagy** [prdatur/phpminer#5]
PHPMAILER has the following code

```
                    $mail->SMTPAuth = true;
                    $mail->SMTPSecure = 'ssl';
```

So the "SMTP Security:" option has no effect, especially when security is set to none

**Comment by DanielNagy** [comment]
Also need to be able to specify a "from" address instead of the message coming from ..

```
Root User root@localhost
```

**Comment by prdatur** [comment]
Have pushed the changes. you can now configurate the from address and check if security was activated and only then use the SMTPAuth + SMTPSecure.
Please test it and tell me if all works well.

**Comment by DanielNagy** [comment]
It seems to work now, however, cannot specify the "name"
ie, it still says Root User `Root User <miners@domain.com>`

Also tried to specify it in the from address, and got this `Root User <Miner > <miners@domain.com>`

**Comment by prdatur** [comment]
added fromname config. please test it.

**Comment by DanielNagy** [comment]
Yep working now. please update version to 1.2.1 so the new version bar disappears :)

**Comment by prdatur** [comment]
:) Will do it tomorrow, need now to go to bed... 7 hours and i need to be awake again :)
