### ISSUE TITLE
Miner start / stop button

### ISSUE THREAD

**Issue by DanielNagy** [prdatur/phpminer#6]
It would be good to have rpcclient start  / stop on command.

Do not restart cgminer if restart is enabled if stop was pushed until start is commanded again.

**Comment by prdatur** [comment]
Pushed it, please test. Notice: after starting it takes a while to get it active again.

**Comment by DanielNagy** [comment]
Start/stop works well.. but, if i kill cgminer manually (with auto restart turned off), the stats disappear, and "Stop rig" is still the text and it says "no devices found or rig is not alive"

The phpminer should know if a connection to rpcclient is still available or not. i recall seeing a ping option, maybe upon cgminer killed/hung/etc, the front end should ping rpcclient on the box.

So i have to press stop rig, so the text changes, then start rig to bring it back

Sure, if i have "auto restart" enabled, it will auto restart it. but my above was based on auto restart turned off.

I also think that when adding a rig, you shouldn't have to add the details to cgminer.. Only details to the rigs rpcclient. it should be upto the RPC client (with preconfigured apilisten/port details), to configure and start the cgminer process.

**Comment by prdatur** [comment]
Hmm this would be a huuuuge change, because phpminer uses very often the direct access to the api and not the rpc. For example to change a pool group, change gpu overclock settings and so on.
The text "no devices found or rig is not alive" is completely correct in this case, because the rig is not stated as "disabled" and therefore it should just say it's offline but not disabled.

**Comment by DanielNagy** [comment]
Yeah i understand that, and that can still be managed i believe.. 

Given that it attempts to talk to the api has also made me notice phpminer web page hang when there's a problem with one of my rigs. I almost believe a rpcclient ping may need to be done prior to attempting to talk to cgminer api.

Infact, the proper way would be to tunnel all the api commands to the cgminer VIA the rpcclient. that way, if cgminer hangs, rpcclient doesn't receive a response(and hangs), rather than bringing the whole phpminer web page down. That way we could show a status of the rig being down properly there. also show cgminer status online/offline via the rpcclient.

**Comment by DanielNagy** [comment]
Also, in tunneling api commands via rpcclient to cgminer, you then can set cgminer to listen only to localhost, rather than potentially another host/network, and leave it open with NO security..

RPC Client has a key at least to stop people accessing it. cgminer does not, only a allow IP list.

**Comment by prdatur** [comment]
api commands will be moved to rpc.
