### ISSUE TITLE
Add custom worker name for each rig in config

### ISSUE THREAD

**Issue by nicoschtein** [prdatur/phpminer#7]
I think it may come in handy to be able to set an option custom worker name (suffix) for each rig on setup.
When we add a new Rig, one more field should be added with:
`Worker Name: [_____]`

This way we can set better more descriptive rig names and keep workers short and simple.

**Comment by prdatur** [comment]
Will add this, this make the "rig based" pool feature more readable.

**Comment by prdatur** [comment]
implemented
