### ISSUE TITLE
[ENHANCEMENT] phpminer_rpcclient Config versioning

### ISSUE THREAD

**Issue by nicoschtein** [prdatur/phpminer#9]
I think there should be a dist config file `phpminer_rpcclient/config.dist.php` with all default values with the repo version, and each user creates a copy `phpminer_rpcclient/config.php` and sets their own values there.

Then phpminer_rpcclient uses `phpminer_rpcclient/config.php` and fails back to `phpminer_rpcclient/config.dist.php` if needed.

Also config versioning could be added. If `phpminer_rpcclient/config.dist.php` version is 1.0.1, and `phpminer_rpcclient/config.php` is <1.0.1 then service should notify the user someway and (depends on backwards compatibility) stops the service until version on `phpminer_rpcclient/config.php` is the same as `phpminer_rpcclient/config.dist.php`.
Normally a user should update config changes and then set the version to the latest, same one from the `phpminer_rpcclient/config.dist.php` file used.

**Comment by prdatur** [comment]
service stop until good version would only work after a rpc service restart, so i think this can be left as it is, but the dist file will be handy, will add this.
